print(' =='*30)
print('                                      LOJA DO ABREU')
print(' =='*30)
print('  10% de desconto nos Pagamentos à Vista ')
print('  8% de Juros à Prazo')
print(' --'*30)
preço = float(input(' Preço do Produto: R$'))
vista = preço-(preço*0.1)
prazo = preço+(preço*0.08)
print(' À vista R${:.2f}\n À prazo R${:.2f}'.format(vista,prazo))
